# Generated by Django 4.2.11 on 2024-03-30 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('product_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('trigger_scrape', models.BooleanField(default=False)),
                ('_trigger_scrape', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductScrapeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_events', to='products.product')),
            ],
        ),
    ]
