# Generated by Django 4.2.11 on 2024-03-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='_trigger_scrape',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trigger_scrape',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, help_text='Scrape Daily?'),
        ),
    ]
